[tox]
isolated_build = True
envlist =
    py310-{pd26,pd29,pd212,pd2x},
    py311-{pd26,pd29,pd212,pd2x},
    py312-{pd26,pd29,pd212,pd2x},
    py313-{pd29,pd212,pd2x},
    py314-{pd212,pd2x}

[testenv]
deps =
    pytest
    pd26: pydantic>=2.0,<2.7
    pd29: pydantic>=2.0,<2.10
    pd212: pydantic>=2.0,<2.13
    pd2x: pydantic>=2.0,<3.0
commands = pytest
