from pydantic.version import VERSION as PYDANTIC_VERSION

PYDANTIC_VERSION_TUPLE = tuple(map(int, PYDANTIC_VERSION.split('.')))
PYDANTIC_GE_V2_13 = PYDANTIC_VERSION_TUPLE >= (2, 13, 0)
PYDANTIC_GE_V2_11 = PYDANTIC_VERSION_TUPLE >= (2, 11, 0)
PYDANTIC_GE_V2_7 = PYDANTIC_VERSION_TUPLE >= (2, 7, 0)
